ar3_arm_controller:
  ros__parameters:
    joints:
      - ar3_joint1
      - ar3_joint2
      - ar3_joint3
      - ar3_joint4
      - ar3_joint5
      - ar3_joint6
    write_op_modes:
      - ar3_joint1
      - ar3_joint2
      - ar3_joint3
      - ar3_joint4
      - ar3_joint5
      - ar3_joint6

ros2_state_controller:
  ros__parameters:
    joints:
      - ar3_joint1
      - ar3_joint2
      - ar3_joint3
      - ar3_joint4
      - ar3_joint5
      - ar3_joint6
    write_op_modes:
      - ar3_joint1
      - ar3_joint2
      - ar3_joint3
      - ar3_joint4
      - ar3_joint5
      - ar3_joint6


fake_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ar3_joint1
      - ar3_joint2
      - ar3_joint3
      - ar3_joint4
      - ar3_joint5
      - ar3_joint6
    write_op_modes:
      - ar3_joint1
      - ar3_joint2
      - ar3_joint3
      - ar3_joint4
      - ar3_joint5
      - ar3_joint6
