controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - ar3_joint1
      - ar3_joint2
      - ar3_joint3
      - ar3_joint4
      - ar3_joint5
      - ar3_joint6
    interface_name: position
